### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by forana** [mikolalysenko/voronoi-diagram#1]
The current example has:

var points = [[
  [1, 0],
  [0, 1],
  [0, 0]
]]

This results in the output:
{ cells: [ [ undefined, undefined, undefined, undefined ] ],
  points: [] }

If the outer brackets are removed, the output becomes:
{ cells: [ [ -1, 0 ], [ -1, 0 ], [ 0, -1 ] ],
  points: [ [ 0.5, 0.5 ] ] }

I suspect this is the intended functionality.

**Comment by mikolalysenko** [comment]
Nice catch!  Fixed.
